[package]
name = "btckey"
version = "0.1.0"
authors = ["Margarita Kitic <rikitau@protonmail.com>"]
edition = "2018"

[dependencies]
bip39 = "1.0.1"
miniscript = { version = "5.1.0", features=["compiler"]}
ring = "0.16.15"
ansi-escapes = "0.1.0"

