[package]
name = "btckey"
version = "0.1.0"
authors = ["Margarita Kitic <rikitau@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.25.0"
bip39 = "1.0.0-rc1"
ring = "0.16.15"
ansi-escapes = "0.1.0"

